import { API_URL } from "./API_URL";
import { PALETTE_COLORS } from "./PALETTE_COLORS";
import { PATHS } from "./PATHS";
import FIELDS_DATA from "./FIELDS_DATA";
import BOOKINGS_DATA from "./BOOKINGS_DATA";
import MONTHS_NAMES from "./MONTHS_NAMES";

export { API_URL, PATHS, PALETTE_COLORS, FIELDS_DATA, BOOKINGS_DATA, MONTHS_NAMES };
